WIP ProofObjects
idris-hackers/software-foundations pull request #31
Opened 2017-07-25 10:51 UTC by clayrat

It seems so far this chapter will be mostly useless for us, as the distinction between proofs and terms they keep talking about doesn't really exist in Idris. Maybe something interesting will come up later.

2017-07-25 11:57 UTC, clayrat commented
Should be ready.

So yeah, in it's current form it's not so useful. It does contain some good-to-know theory, but if you've made it this far, you most likely already have some intuitive understanding of the things it talks about. 

We could try putting it earlier in the book, but it talks about `IndProp`-level stuff. So not sure what to do with it for now.

2017-07-25 18:55 UTC, yurrriq commented
Let's keep collecting the rough translations and we can edit later. Maybe after ten chapters we should focus on editing and then do a "release" (merge to master and regenerate the PDF).

2017-07-25 18:59 UTC, clayrat commented
According to the book itself, the first part ("Logical Foundations") ends after `Rel`, the other part ("Programming Foundations") then starts focusing on modelling lambda calculus and such. So that might be a good point to do editing.

2017-07-25 19:04 UTC, yurrriq commented
Sounds like a solid plan to me.

2017-07-26 13:24 UTC, clayrat commented
Any remarks/edits on this chapter specifically?

2017-07-28 17:21 UTC, yurrriq commented
I've been busy, but will make sure to review this and the other PRs properly by Monday at the latest.

2017-07-31 13:10 UTC, yurrriq commented
I've got some comments and edits locally. Will post them tonight.

2017-08-01 09:30 UTC, clayrat commented
So, according to https://softwarefoundations.cis.upenn.edu/draft/lf-current/toc.html , "Logical foundations" actually end on `Auto`, not `Rel`. We should still probably review drafts every 6-8 chapters.

2017-08-01 13:42 UTC, yurrriq commented
Cool. Let's do a "release" up to Auto then and merge Rel in lot develop after. I got a bit sick last night and likely won't have time tonight, but I can definitely review all the PRs that are ready tomorrow.

2017-08-01 13:59 UTC, yurrriq requested changes

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +\todo[inline]{Edit, this actually is wrong, stdlib uses \idr{%runElab} to define
We should use just `\idr{runElab}` until we solve #22.

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +Definition ev_plus4' : ∀n, ev n -> ev (4 + n) :=
Let's use `forall` so as not to upset minted.

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +\[
We'll need to add the following to `book.tex`:

```tex
- \usepackage{dirtytalk}
```

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +  \say{"\textit{Algorithms are the computational content of proofs.}" - Robert
This works for me:

```latex
\say{Algorithms are the computational content of proofs.} -- Robert Harper
```

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +==== Exercise: 2 stars, optional (or_commut'')
`or_commut''` should be `or_comm`

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +=== \idr{Unit} and \idr{Void}
Here's a dirty hack to work around #24:

```diff
-=== \idr{Unit} and \idr{Void}
+\subsection{\idr{Unit} and \idr{Void}}
```

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +Definition and_comm' P Q : P ∧ Q ↔ Q ∧ P :=
`/\` `<->` `/\`

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +Definition and_comm'_aux P Q (H : P ∧ Q) :=
`/\`

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +expresses this functionality, in the same way that the polymorphic type \idr{{x
`\idr{...}` needs to be on one line

2017-08-01 13:59 UTC, yurrriq commented on src/ProofObjects.lidr
> +adds this fact to the context.
Here's a diff with all my suggestions:

````diff
diff --git a/src/ProofObjects.lidr b/src/ProofObjects.lidr
index 7e465b3..2f24cd4 100644
--- a/src/ProofObjects.lidr
+++ b/src/ProofObjects.lidr
@@ -2,10 +2,7 @@
 
 > module ProofObjects
 
-\[
-  \say{"\textit{Algorithms are the computational content of proofs.}" - Robert
-Harper}
-\]
+\say{Algorithms are the computational content of proofs.} -- Robert Harper
 
 We have seen that Idris has mechanisms both for _programming_, using inductive
 data types like \idr{Nat} or \idr{List} and functions over these types, and for
@@ -103,9 +100,10 @@ wants to be further applied to evidence that that number is even; its type,
       {n : Nat} -> Ev n -> Ev (S (S n))
 ```
 
-expresses this functionality, in the same way that the polymorphic type \idr{{x
-: Type} -> List x} expresses the fact that the constructor \idr{Nil} can be
-thought of as a function from types to empty lists with elements of that type.
+expresses this functionality, in the same way that the polymorphic type
+\idr{{x : Type} -> List x} expresses the fact that the constructor \idr{Nil} can
+be thought of as a function from types to empty lists with elements of that
+type.
 
 \todo[inline]{Edit or remove}
 
@@ -219,7 +217,7 @@ n)} — that is, a function that takes two arguments (one number and a piece of
 evidence) and returns a piece of evidence! Here it is:
 
 ```coq
-Definition ev_plus4' : ∀n, ev n -> ev (4 + n) :=
+Definition ev_plus4' : forall n, ev n -> ev (4 + n) :=
   fun (n : Nat) => fun (H : ev n) =>
     ev_SS (S (S n)) (ev_SS n H).
 ```
@@ -359,12 +357,12 @@ we've been doing. We can also use it to build proofs directly, using
 pattern-matching. For instance:
 
 ```coq
-Definition and_comm'_aux P Q (H : P ∧ Q) :=
+Definition and_comm'_aux P Q (H : P /\ Q) :=
   match H with
   | conj HP HQ => conj HQ HP
   end.
 
-Definition and_comm' P Q : P ∧ Q ↔ Q ∧ P :=
+Definition and_comm' P Q : P /\ Q <-> Q /\ P :=
   conj (and_comm'_aux P Q) (and_comm'_aux Q P).
 ```
 
@@ -396,11 +394,11 @@ Once again, we can also directly write proof objects for theorems involving
 \idr{Or}, without resorting to tactics.
 
 
-==== Exercise: 2 stars, optional (or_commut'')
+==== Exercise: 2 stars, optional (or_comm)
 
 \ \todo[inline]{Edit}
 
-Try to write down an explicit proof object for \idr{or_commut} (without using
+Try to write down an explicit proof object for \idr{or_comm} (without using
 `Print` to peek at the ones we already defined!).
 
 > or_comm : Or p q -> Or q p
@@ -450,7 +448,7 @@ Complete the definition of the following proof object:
 $\square$
 
 
-=== \idr{Unit} and \idr{Void}
+\subsection{\idr{Unit} and \idr{Void}}
 
 The inductive definition of the \idr{Unit} proposition is simple:
 
@@ -465,7 +463,7 @@ a proof of\idr{Unit} is not informative.)
 \idr{Void} is equally simple — indeed, so simple it may look syntactically wrong
 at first glance!
 
-\todo[inline]{Edit, this actually is wrong, stdlib uses \idr{%runElab} to define
+\todo[inline]{Edit, this actually is wrong, stdlib uses \idr{runElab} to define
 it}
 
 ```idris
@@ -570,8 +568,8 @@ In general, the `inversion` tactic...
     - adds these equalities to the context (and, for convenience, rewrites them
       in the goal), and
 
-    - if the equalities are not satisfiable (e.g., they involve things like `S n
-      = Z`), immediately solves the subgoal.
+    - if the equalities are not satisfiable (e.g., they involve things like
+      \idr{S n = Z}), immediately solves the subgoal.
 
 _Example_: If we invert a hypothesis built with \idr{Or}, there are two
 constructors, so two subgoals get generated. The conclusion (result type) of the
diff --git a/src/book.tex b/src/book.tex
index a7632b4..6ee6846 100644
--- a/src/book.tex
+++ b/src/book.tex
@@ -42,6 +42,7 @@ header-includes:
 - \usepackage{todonotes}
 -
 - \usepackage{ebproof}
+- \usepackage{dirtytalk}
 include-before: \frontmatter
 ---
 
````

2017-08-01 14:01 UTC, clayrat commented
But `Auto` isn't done yet, it's like 5 chapters after `Rel` in the new version :) My point was that the "first part" doesn't end as fast as I thought.

2017-08-01 14:16 UTC, yurrriq commented
Ha, ok. I misunderstood. :+1: to a "release" after Rel then.

2017-08-03 02:56 UTC, yurrriq requested changes

2017-08-03 02:56 UTC, yurrriq commented on src/ProofObjects.lidr
> +\say{"\textit{Algorithms are the computational content of proofs.}" - Robert
This results in the following in the PDF.

> “”Algorithms are the computational content of proofs.” - Robert Harper”

I'm not married to this exact solution, but I don't like the double quotes as it is now.

2017-08-03 02:56 UTC, yurrriq commented on src/ProofObjects.lidr
> +\say{"\textit{Algorithms are the computational content of proofs.}" - Robert
```tex
\say{\textit{Algorithms are the computational content of proofs.}}
-- Robert Harper
```

... results in:

> “Algorithms are the computational content of proofs.” – Robert Harper

2017-08-03 02:57 UTC, yurrriq commented
Actually I'm just gonna merge this and #33 and make the `\say` tweak. Thanks!

2017-08-03 02:57 UTC, yurrriq approved these changes

2017-08-03 02:58 UTC, merged