WIP Rel
idris-hackers/software-foundations pull request #33
Opened 2017-07-25 13:17 UTC by clayrat

2017-07-26 13:24 UTC, clayrat commented
Ready for review.

2017-08-01 14:15 UTC, yurrriq requested changes
We'll need to add `Rel` to `software_foundations.ipkg` and `Rel.lidr` to `src/Makefile` too.

2017-08-01 14:15 UTC, yurrriq commented on src/Rel.lidr
> +Show that the idr{Total_relation} defined in earlier is not a partial function.
```tex
\idr{Total_relation}
```

2017-08-01 14:15 UTC, yurrriq commented on src/Rel.lidr
> +Show that the idr{Empty_relation} that we defined earlier is a partial function.
```tex
\idr{Empty_relation}
```

2017-08-01 14:15 UTC, yurrriq commented on src/Rel.lidr
> +> next_nat_closure_is_le : (n <=' m) <-> (Clos_refl_trans Next_nat n m)
Note for later: minted handles this definition poorly. See also #30.

2017-08-01 14:15 UTC, yurrriq commented
Other than those little comments this looks good to me.

2017-08-01 14:17 UTC, yurrriq commented
Feel free to merge this one yourself after those trivial changes.

2017-08-01 14:28 UTC, clayrat commented on src/Rel.lidr
> +> next_nat_closure_is_le : (n <=' m) <-> (Clos_refl_trans Next_nat n m)
So what should we do here? Add a `todo`?

2017-08-02 05:54 UTC, yurrriq commented
Sure, though linking the relevant issue in my previous  comment might be enough. This is a toolchain issue rather than a code one.

2017-08-02 10:46 UTC, clayrat commented
Let's merge `ProofObjects` first maybe and add to `.ipkg`/`Makefile` after that? I feel like it'll be a merge conflict anyway.

2017-08-03 02:35 UTC, yurrriq approved these changes

2017-08-03 02:58 UTC, merged